# --- 
# - name: "update apt packages."
#   become: true
#   apt:
#     update_cache: yes

# - name: "upgrade packages"
#   become: true
#   apt:
#     upgrade: yes

# - name: "install python"
#   become: true
#   apt:
#     name: python
#     state: latest
#     update_cache: yes

# - name: "install nodejs and npm"
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

---
- name: 'update and upgrade packages.' # sudo apt upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
    
- name: remove unneeded dependencies
  become: true
  apt:
    autoremove: yes

- name: "Install NodeJs 13"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes
- name: "move enviroment variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d